"""Physics-flavoured synthetic SCADA generator.

The generator produces multi-turbine time series that reproduce the qualitative
relationships an engineer would expect from a pitch-regulated, variable-speed
turbine.  It is *not* a model of any specific commercial machine; it exists so
the whole pipeline can be exercised end-to-end without a proprietary dataset.

Modelled relationships
----------------------
* **Wind resource** - an Ornstein-Uhlenbeck process with a diurnal component,
  per-turbine mean and a shared farm-level driver, so turbines are correlated
  but not identical.
* **Power curve** - zero below cut-in, cubic ramp to rated wind speed, flat at
  rated power up to cut-out, zero above.  Multiplied by a per-turbine
  efficiency and by the degradation-driven efficiency loss.
* **Drivetrain speeds** - rotor speed tracks wind speed up to rated, generator
  speed is the rotor speed times a fixed gear ratio plus slip noise.
* **Thermal model** - every temperature is a first-order lag (exponential
  smoothing) towards a target that depends on ambient temperature and on the
  heat generated by the current load.  This produces genuine thermal inertia,
  so instantaneous temperature is not a deterministic function of load.
* **Vibration** - baseline scales with rotor speed, plus a component that grows
  with mechanical degradation and an occasional transient.
* **Lubrication / hydraulics** - oil pressure falls and becomes noisier as
  lubrication degrades; oil temperature rises as pressure falls (poorer film,
  more friction).

Degradation and failures
------------------------
Each turbine experiences degradation *episodes*.  An episode has a failure mode
(gearbox, generator, bearing, lubrication, hydraulic) and a ramp over which its
severity grows from 0 to a peak following a smooth, noisy curve.  Crucially,
only ``1 - benign_degradation_ratio`` of episodes terminate in a failure; the
rest peak and heal.  This keeps the target learnable but not trivial: no single
sensor threshold separates the classes, and a rising trend is necessary but not
sufficient evidence of an imminent failure.

After a failure the turbine enters ``fault`` then ``maintenance`` for a repair
window, degradation resets to zero, and a recovery period follows in which
component condition is restored.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np
import pandas as pd

from wind_turbine_pm.config import Config
from wind_turbine_pm.constants import (
    FAILURE_EVENT,
    MAINTENANCE_EVENT,
    OPERATIONAL_STATUS,
    TIMESTAMP,
    TURBINE_ID,
    FailureMode,
    OperationalStatus,
)
from wind_turbine_pm.logging_config import get_logger
from wind_turbine_pm.utils.reproducibility import rng_for

logger = get_logger(__name__)

HOURS_PER_YEAR = 8766.0
GEAR_RATIO = 97.0

#: How strongly each failure mode drives each sensor channel. Values are
#: multipliers applied to the episode severity in [0, 1].
MODE_EFFECTS: dict[str, dict[str, float]] = {
    FailureMode.GEARBOX: {
        "vibration": 3.4,
        "gearbox_temperature": 14.0,
        "oil_temperature": 6.0,
        "oil_pressure": -0.9,
        "efficiency": -0.06,
    },
    FailureMode.GENERATOR: {
        "generator_temperature": 20.0,
        "nacelle_temperature": 4.0,
        "vibration": 1.1,
        "efficiency": -0.08,
    },
    FailureMode.BEARING: {
        "bearing_temperature": 17.0,
        "vibration": 3.9,
        "gearbox_temperature": 4.0,
        "efficiency": -0.03,
    },
    FailureMode.LUBRICATION: {
        "oil_pressure": -1.6,
        "oil_temperature": 11.0,
        "gearbox_temperature": 7.0,
        "bearing_temperature": 6.0,
        "vibration": 1.6,
        "efficiency": -0.04,
    },
    FailureMode.HYDRAULIC: {
        "hydraulic_pressure": -55.0,
        "oil_pressure": -0.5,
        "brake_temperature": 22.0,
        "vibration": 0.8,
        "efficiency": -0.05,
    },
}


@dataclass(frozen=True)
class TurbineProfile:
    """Per-turbine baseline characteristics.

    Different turbines sit at different operating points, which forces the model
    to rely on turbine-relative features rather than absolute thresholds.
    """

    turbine_id: str
    mean_wind_speed: float
    efficiency: float
    rated_power_kw: float
    thermal_offset: float
    vibration_baseline: float
    oil_pressure_baseline: float
    hydraulic_baseline: float
    failure_propensity: float


@dataclass
class Episode:
    """A degradation episode on a single turbine.

    Attributes:
        mode: Which subsystem is degrading.
        start_index: First row index of the ramp.
        peak_index: Row index at which severity is highest.
        ends_in_failure: Whether the episode terminates in a failure event.
        peak_severity: Maximum severity in ``[0, 1]``.
        heal_index: Row index by which a benign episode has fully healed.
    """

    mode: str
    start_index: int
    peak_index: int
    ends_in_failure: bool
    peak_severity: float
    heal_index: int
    episode_id: int = 0
    failure_index: int | None = None
    repair_end_index: int | None = None
    severity_profile: np.ndarray = field(default_factory=lambda: np.empty(0))


# ---------------------------------------------------------------------------
# Profiles and wind
# ---------------------------------------------------------------------------
def build_profiles(n_turbines: int, seed: int) -> list[TurbineProfile]:
    """Create deterministic per-turbine baseline profiles.

    Args:
        n_turbines: Number of turbines to simulate.
        seed: Base random seed.

    Returns:
        A list of :class:`TurbineProfile`, one per turbine.
    """
    profiles: list[TurbineProfile] = []
    for index in range(n_turbines):
        turbine_id = f"T{index + 1:02d}"
        rng = rng_for(seed, "profile", turbine_id)
        profiles.append(
            TurbineProfile(
                turbine_id=turbine_id,
                mean_wind_speed=float(rng.uniform(6.4, 9.6)),
                efficiency=float(rng.uniform(0.92, 1.03)),
                rated_power_kw=2000.0,
                thermal_offset=float(rng.uniform(-4.0, 5.0)),
                vibration_baseline=float(rng.uniform(1.5, 2.6)),
                oil_pressure_baseline=float(rng.uniform(4.6, 5.8)),
                hydraulic_baseline=float(rng.uniform(175.0, 205.0)),
                failure_propensity=float(rng.uniform(0.6, 1.5)),
            )
        )
    return profiles


def _ou_process(n: int, rng: np.random.Generator, theta: float, sigma: float) -> np.ndarray:
    """Generate a mean-reverting Ornstein-Uhlenbeck path with zero mean."""
    path = np.empty(n, dtype=float)
    value = 0.0
    for index in range(n):
        value += -theta * value + sigma * rng.standard_normal()
        path[index] = value
    return path


def simulate_wind(
    n: int,
    hours: np.ndarray,
    day_of_year: np.ndarray,
    profile: TurbineProfile,
    farm_driver: np.ndarray,
    rng: np.random.Generator,
) -> np.ndarray:
    """Simulate a non-negative wind-speed series.

    The series combines a shared farm-level driver (weather fronts affect the
    whole site), a turbine-specific mean-reverting component, a diurnal cycle
    and a mild seasonal cycle.

    Args:
        n: Number of samples.
        hours: Hour-of-day for each sample.
        day_of_year: Day-of-year for each sample.
        profile: The turbine's baseline profile.
        farm_driver: Shared zero-mean driver of length ``n``.
        rng: Random generator for this turbine.

    Returns:
        Wind speed in m/s, clipped at zero.
    """
    local = _ou_process(n, rng, theta=0.06, sigma=0.55)
    diurnal = 1.05 * np.sin(2 * np.pi * (hours - 15.0) / 24.0)
    seasonal = 1.4 * np.cos(2 * np.pi * (day_of_year - 15.0) / 365.25)
    gusts = rng.gamma(shape=1.4, scale=0.42, size=n) - 0.59
    wind = profile.mean_wind_speed + 0.85 * farm_driver + local + diurnal + seasonal + gusts
    return np.clip(wind, 0.0, 40.0)


def power_curve(wind: np.ndarray, rated_power: float, cut_in: float, rated_wind: float, cut_out: float) -> np.ndarray:
    """Evaluate an idealised pitch-regulated power curve.

    Args:
        wind: Wind speed in m/s.
        rated_power: Rated electrical power in kW.
        cut_in: Cut-in wind speed in m/s.
        rated_wind: Rated wind speed in m/s.
        cut_out: Cut-out wind speed in m/s.

    Returns:
        Theoretical power output in kW.
    """
    power = np.zeros_like(wind, dtype=float)
    ramp = (wind >= cut_in) & (wind < rated_wind)
    power[ramp] = rated_power * ((wind[ramp] - cut_in) / (rated_wind - cut_in)) ** 3
    power[(wind >= rated_wind) & (wind <= cut_out)] = rated_power
    return power


def _first_order_lag(target: np.ndarray, alpha: float, initial: float) -> np.ndarray:
    """Apply exponential smoothing, giving the series thermal inertia."""
    out = np.empty_like(target)
    state = initial
    for index in range(target.size):
        state += alpha * (target[index] - state)
        out[index] = state
    return out


# ---------------------------------------------------------------------------
# Episodes
# ---------------------------------------------------------------------------
def _severity_curve(length: int, peak: float, rng: np.random.Generator) -> np.ndarray:
    """Smooth, noisy, monotone-ish ramp from ~0 to ``peak``."""
    if length <= 1:
        return np.full(max(length, 0), peak)
    position = np.linspace(0.0, 1.0, length)
    # Logistic ramp with a random inflection point and steepness.
    inflection = rng.uniform(0.45, 0.75)
    steepness = rng.uniform(6.0, 11.0)
    base = 1.0 / (1.0 + np.exp(-steepness * (position - inflection)))
    base = (base - base[0]) / max(base[-1] - base[0], 1e-9)
    wobble = np.cumsum(rng.normal(0.0, 0.02, size=length))
    wobble -= np.linspace(0.0, wobble[-1], length)
    return np.clip((base + wobble) * peak, 0.0, 1.0)


def plan_episodes(
    n: int,
    profile: TurbineProfile,
    cfg: Config,
    rng: np.random.Generator,
) -> list[Episode]:
    """Lay out non-overlapping degradation episodes across a turbine's timeline.

    Episodes are spread over the whole record rather than packed from the start:
    the timeline is divided into one slot per episode and each episode is placed
    inside its own slot.  This matters for the chronological split - a planner
    that walks a cursor forward concentrates every failure in the training
    period and leaves the test split with no positive labels at all.

    Args:
        n: Number of time steps.
        profile: Turbine profile (its propensity scales the episode count).
        cfg: Merged configuration.
        rng: Random generator for this turbine.

    Returns:
        Chronologically ordered episodes.
    """
    steps_per_hour = float(cfg.require("synthetic._steps_per_hour"))
    total_hours = n / steps_per_hour
    rate = float(cfg.require("synthetic.failures_per_turbine_per_year"))
    benign_ratio = float(cfg.require("synthetic.benign_degradation_ratio"))

    expected_failures = rate * profile.failure_propensity * total_hours / HOURS_PER_YEAR
    expected_episodes = expected_failures / max(1.0 - benign_ratio, 1e-6)
    n_episodes = int(rng.poisson(max(expected_episodes, 0.0)))
    if n_episodes <= 0:
        return []

    ramp_min = int(float(cfg.require("synthetic.degradation_hours_min")) * steps_per_hour)
    ramp_max = int(float(cfg.require("synthetic.degradation_hours_max")) * steps_per_hour)
    repair_min = int(float(cfg.require("synthetic.repair_hours_min")) * steps_per_hour)
    repair_max = int(float(cfg.require("synthetic.repair_hours_max")) * steps_per_hour)
    recovery = int(float(cfg.require("synthetic.recovery_hours")) * steps_per_hour)

    slot = n / n_episodes
    # Budget reserved after the peak for repair plus post-maintenance recovery.
    tail_budget = repair_max + recovery
    if slot <= ramp_min + tail_budget:
        # The record is too short to host this many well-separated episodes.
        n_episodes = max(int(n // (ramp_min + tail_budget + 1)), 0)
        if n_episodes <= 0:
            return []
        slot = n / n_episodes

    episodes: list[Episode] = []
    modes = list(MODE_EFFECTS)

    for episode_id in range(n_episodes):
        slot_start = int(episode_id * slot)
        slot_end = int((episode_id + 1) * slot)
        usable = slot_end - slot_start - tail_budget
        if usable <= ramp_min:
            continue

        ramp = int(rng.integers(ramp_min, min(ramp_max, usable) + 1))
        # Jitter the peak inside the slot so failures do not fall on a grid.
        latest_peak = slot_start + usable
        earliest_peak = slot_start + ramp
        peak_index = int(rng.integers(earliest_peak, latest_peak + 1))
        start_index = peak_index - ramp
        if start_index < 0 or peak_index >= n:
            continue

        ends_in_failure = bool(rng.random() >= benign_ratio)
        peak_severity = float(rng.uniform(0.75, 1.0) if ends_in_failure else rng.uniform(0.35, 0.85))
        heal = int(rng.integers(max(ramp_min // 2, 1), max(ramp_min * 2, 2)))

        episode = Episode(
            mode=str(rng.choice(modes)),
            start_index=start_index,
            peak_index=peak_index,
            ends_in_failure=ends_in_failure,
            peak_severity=peak_severity,
            heal_index=min(peak_index + heal, n - 1),
            episode_id=episode_id,
        )
        episode.severity_profile = _severity_curve(ramp, peak_severity, rng)

        if ends_in_failure:
            episode.failure_index = peak_index
            repair = int(rng.integers(repair_min, repair_max + 1))
            episode.repair_end_index = min(peak_index + repair, n - 1)

        episodes.append(episode)

    return episodes


def _build_severity_series(n: int, episodes: list[Episode]) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Expand episodes into per-step severity, mode and episode-id arrays."""
    severity = np.zeros(n, dtype=float)
    mode = np.full(n, "", dtype=object)
    episode_ids = np.full(n, -1, dtype=int)

    for episode in episodes:
        ramp_slice = slice(episode.start_index, episode.peak_index)
        ramp_length = ramp_slice.stop - ramp_slice.start
        if ramp_length > 0:
            severity[ramp_slice] = episode.severity_profile[:ramp_length]
            mode[ramp_slice] = episode.mode
            episode_ids[ramp_slice] = episode.episode_id

        if episode.ends_in_failure:
            # The failure row is the peak of the episode, not the start of a
            # healthy period: without this the severity series drops to zero at
            # exactly the moment of failure.
            severity[episode.peak_index] = episode.peak_severity
            mode[episode.peak_index] = episode.mode
            episode_ids[episode.peak_index] = episode.episode_id

        if not episode.ends_in_failure:
            decay_slice = slice(episode.peak_index, episode.heal_index + 1)
            decay_length = decay_slice.stop - decay_slice.start
            if decay_length > 0:
                severity[decay_slice] = np.linspace(episode.peak_severity, 0.0, decay_length)
                mode[decay_slice] = episode.mode
                episode_ids[decay_slice] = episode.episode_id

    return severity, mode, episode_ids


# ---------------------------------------------------------------------------
# Single-turbine simulation
# ---------------------------------------------------------------------------
def simulate_turbine(
    profile: TurbineProfile,
    index: pd.DatetimeIndex,
    ambient: np.ndarray,
    farm_driver: np.ndarray,
    cfg: Config,
    seed: int,
) -> pd.DataFrame:
    """Simulate the full SCADA record for one turbine.

    Args:
        profile: Turbine baseline characteristics.
        index: Shared time index for the whole farm.
        ambient: Site ambient temperature series (degC).
        farm_driver: Shared wind driver.
        cfg: Merged configuration.
        seed: Base random seed.

    Returns:
        A dataframe with one row per timestamp for this turbine.
    """
    rng = rng_for(seed, "sim", profile.turbine_id)
    n = len(index)
    steps_per_hour = float(cfg.require("synthetic._steps_per_hour"))
    hours = index.hour.to_numpy(dtype=float) + index.minute.to_numpy(dtype=float) / 60.0
    day_of_year = index.dayofyear.to_numpy(dtype=float)

    wind = simulate_wind(n, hours, day_of_year, profile, farm_driver, rng)
    episodes = plan_episodes(n, profile, cfg, rng)
    severity, mode, episode_ids = _build_severity_series(n, episodes)

    # --- Operating state --------------------------------------------------
    status = np.full(n, str(OperationalStatus.NORMAL), dtype=object)
    failure_event = np.zeros(n, dtype=np.int8)
    maintenance_event = np.zeros(n, dtype=np.int8)
    availability = np.ones(n, dtype=float)

    for episode in episodes:
        if episode.failure_index is None or episode.repair_end_index is None:
            continue
        failure_event[episode.failure_index] = 1
        fault_end = min(episode.failure_index + int(2 * steps_per_hour), n)
        status[episode.failure_index : fault_end] = str(OperationalStatus.FAULT)
        status[fault_end : episode.repair_end_index + 1] = str(OperationalStatus.MAINTENANCE)
        maintenance_event[episode.repair_end_index] = 1
        availability[episode.failure_index : episode.repair_end_index + 1] = 0.0

    # Scheduled (non-failure) maintenance windows.
    scheduled_rate = float(cfg.require("synthetic.scheduled_maintenance_per_year"))
    n_scheduled = int(rng.poisson(scheduled_rate * (n / steps_per_hour) / HOURS_PER_YEAR))
    for _ in range(n_scheduled):
        start = int(rng.integers(0, n))
        duration = int(rng.integers(4, 13) * steps_per_hour)
        end = min(start + duration, n - 1)
        if failure_event[start:end].any() or (availability[start:end] == 0).any():
            continue
        status[start:end] = str(OperationalStatus.MAINTENANCE)
        maintenance_event[end] = 1
        availability[start:end] = 0.0

    # Idle below cut-in / above cut-out; derated occasionally under high load.
    cut_in = float(cfg.require("features.interactions.cut_in_wind_speed"))
    cut_out = float(cfg.require("features.interactions.cut_out_wind_speed"))
    rated_wind = float(cfg.require("features.interactions.rated_wind_speed"))
    idle_mask = ((wind < cut_in) | (wind > cut_out)) & (availability > 0)
    status[idle_mask] = str(OperationalStatus.IDLE)

    derate_factor = np.ones(n, dtype=float)
    derate_candidates = np.where((wind > rated_wind) & (availability > 0) & ~idle_mask)[0]
    if derate_candidates.size:
        chosen = derate_candidates[rng.random(derate_candidates.size) < 0.03]
        for start in chosen:
            end = min(start + int(rng.integers(1, 5) * steps_per_hour), n)
            status[start:end] = str(OperationalStatus.DERATED)
            derate_factor[start:end] = rng.uniform(0.45, 0.8)

    running = (availability > 0) & ~idle_mask

    # --- Power and drivetrain --------------------------------------------
    theoretical = power_curve(wind, profile.rated_power_kw, cut_in, rated_wind, cut_out)
    efficiency_loss = np.zeros(n, dtype=float)
    for mode_name, effects in MODE_EFFECTS.items():
        mask = mode == mode_name
        if mask.any():
            efficiency_loss[mask] += effects.get("efficiency", 0.0) * severity[mask]

    power = theoretical * profile.efficiency * (1.0 + efficiency_loss) * derate_factor
    power = np.where(running, power, 0.0)
    power += rng.normal(0.0, 18.0, size=n) * running
    power = np.clip(power, -20.0, profile.rated_power_kw * 1.12)

    tip_ratio = np.clip(wind / max(rated_wind, 1e-6), 0.0, 1.0)
    rotor_speed = np.where(running, 5.5 + 9.5 * tip_ratio + rng.normal(0.0, 0.16, size=n), 0.0)
    rotor_speed = np.clip(rotor_speed, 0.0, 18.0)
    generator_speed = rotor_speed * GEAR_RATIO * (1.0 + rng.normal(0.0, 0.004, size=n))
    generator_speed = np.clip(generator_speed, 0.0, 2000.0)

    load = np.clip(power / profile.rated_power_kw, 0.0, 1.2)

    # --- Severity contributions per channel -------------------------------
    def mode_effect(channel: str) -> np.ndarray:
        effect = np.zeros(n, dtype=float)
        for mode_name, effects in MODE_EFFECTS.items():
            if channel not in effects:
                continue
            mask = mode == mode_name
            if mask.any():
                effect[mask] += effects[channel] * severity[mask]
        return effect

    # --- Thermal model ----------------------------------------------------
    alpha_slow = float(np.clip(0.10 / steps_per_hour * steps_per_hour, 0.05, 0.35))
    gearbox_target = ambient + 18.0 + 44.0 * load + profile.thermal_offset + mode_effect("gearbox_temperature")
    gearbox_temperature = _first_order_lag(gearbox_target, alpha=alpha_slow, initial=float(gearbox_target[0]))

    generator_target = ambient + 22.0 + 58.0 * load + profile.thermal_offset + mode_effect("generator_temperature")
    generator_temperature = _first_order_lag(generator_target, alpha=alpha_slow * 1.4, initial=float(generator_target[0]))

    bearing_target = ambient + 14.0 + 33.0 * load + 0.55 * profile.thermal_offset + mode_effect("bearing_temperature")
    bearing_temperature = _first_order_lag(bearing_target, alpha=alpha_slow * 0.85, initial=float(bearing_target[0]))

    nacelle_target = ambient + 6.0 + 11.0 * load + 0.3 * profile.thermal_offset + mode_effect("nacelle_temperature")
    nacelle_temperature = _first_order_lag(nacelle_target, alpha=alpha_slow * 1.8, initial=float(nacelle_target[0]))

    # --- Lubrication: pressure first, then temperature reacts to it -------
    oil_pressure = (
        profile.oil_pressure_baseline
        + 0.42 * load
        + mode_effect("oil_pressure")
        + rng.normal(0.0, 0.06, size=n)
    )
    # Degradation also destabilises the pressure signal (rising variance).
    oil_pressure += rng.normal(0.0, 1.0, size=n) * 0.22 * severity
    oil_pressure = np.clip(np.where(running, oil_pressure, oil_pressure * 0.35), 0.05, 11.0)

    pressure_deficit = np.clip(profile.oil_pressure_baseline - oil_pressure, 0.0, None)
    oil_target = (
        ambient + 12.0 + 30.0 * load + 5.2 * pressure_deficit + mode_effect("oil_temperature")
    )
    oil_temperature = _first_order_lag(oil_target, alpha=alpha_slow * 0.7, initial=float(oil_target[0]))

    hydraulic_pressure = (
        profile.hydraulic_baseline
        - 6.0 * load
        + mode_effect("hydraulic_pressure")
        + rng.normal(0.0, 2.4, size=n)
    )
    hydraulic_pressure = np.clip(np.where(running, hydraulic_pressure, hydraulic_pressure * 0.9), 0.0, 290.0)

    brake_target = ambient + 5.0 + 6.0 * load + mode_effect("brake_temperature")
    brake_temperature = _first_order_lag(brake_target, alpha=alpha_slow * 2.2, initial=float(brake_target[0]))

    # --- Vibration --------------------------------------------------------
    vibration = (
        profile.vibration_baseline
        + 0.115 * rotor_speed
        + 0.55 * load
        + mode_effect("vibration")
        + rng.normal(0.0, 0.19, size=n)
    )
    # Degradation increases both level and variability.
    vibration += np.abs(rng.normal(0.0, 1.0, size=n)) * 0.42 * severity
    transients = rng.random(n) < 0.004
    vibration[transients] += rng.uniform(0.6, 2.0, size=int(transients.sum()))
    vibration = np.clip(np.where(running, vibration, vibration * 0.22), 0.0, 24.0)

    nacelle_temperature = np.clip(nacelle_temperature + rng.normal(0.0, 0.5, size=n), -40.0, 85.0)

    hours_to_failure = np.full(n, np.nan, dtype=float)
    for episode in episodes:
        if episode.failure_index is None:
            continue
        window_start = max(episode.start_index, 0)
        offsets = np.arange(window_start, episode.failure_index + 1)
        hours_to_failure[offsets] = (episode.failure_index - offsets) / steps_per_hour

    frame = pd.DataFrame(
        {
            TIMESTAMP: index,
            TURBINE_ID: profile.turbine_id,
            "wind_speed": wind,
            "rotor_speed": rotor_speed,
            "generator_speed": generator_speed,
            "power_output": power,
            "generator_temperature": generator_temperature + rng.normal(0.0, 0.35, size=n),
            "gearbox_temperature": gearbox_temperature + rng.normal(0.0, 0.3, size=n),
            "bearing_temperature": bearing_temperature + rng.normal(0.0, 0.28, size=n),
            "oil_temperature": oil_temperature + rng.normal(0.0, 0.25, size=n),
            "oil_pressure": oil_pressure,
            "vibration": vibration,
            "ambient_temperature": ambient + rng.normal(0.0, 0.22, size=n),
            "nacelle_temperature": nacelle_temperature,
            "hydraulic_pressure": hydraulic_pressure,
            "brake_temperature": brake_temperature,
            OPERATIONAL_STATUS: status,
            FAILURE_EVENT: failure_event,
            MAINTENANCE_EVENT: maintenance_event,
            "degradation_level": severity,
            "failure_mode": mode,
            "episode_id": episode_ids,
            "hours_to_failure": hours_to_failure,
        }
    )
    return frame


# ---------------------------------------------------------------------------
# Data-quality injection
# ---------------------------------------------------------------------------
def inject_data_quality_issues(frame: pd.DataFrame, cfg: Config, seed: int) -> pd.DataFrame:
    """Add missing values, out-of-range readings and duplicate rows.

    These defects are what the validation layer is built to detect; generating
    them here means the validation tests exercise real data rather than mocks.

    Args:
        frame: Clean generated frame.
        cfg: Merged configuration.
        seed: Base random seed.

    Returns:
        A new frame with injected defects.
    """
    rng = rng_for(seed, "quality")
    out = frame.copy()
    sensor_columns = [
        column
        for column in cfg.require("features.raw_sensors")
        if column in out.columns
    ]
    n_rows = len(out)

    missing_rate = float(cfg.require("synthetic.missing_rate"))
    if missing_rate > 0:
        for column in sensor_columns:
            mask = rng.random(n_rows) < missing_rate
            out.loc[mask, column] = np.nan

    invalid_rate = float(cfg.require("synthetic.invalid_rate"))
    if invalid_rate > 0:
        impossible = {
            "wind_speed": -7.5,
            "rotor_speed": 99.0,
            "power_output": -5000.0,
            "gearbox_temperature": 999.0,
            "oil_pressure": -3.0,
            "vibration": 500.0,
            "ambient_temperature": -99.0,
            "hydraulic_pressure": 9999.0,
        }
        for column, bad_value in impossible.items():
            if column not in out.columns:
                continue
            mask = rng.random(n_rows) < invalid_rate
            out.loc[mask, column] = bad_value

    duplicate_rate = float(cfg.require("synthetic.duplicate_rate"))
    if duplicate_rate > 0:
        n_duplicates = int(n_rows * duplicate_rate)
        if n_duplicates > 0:
            picks = rng.choice(n_rows, size=n_duplicates, replace=False)
            out = pd.concat([out, out.iloc[picks]], ignore_index=True)

    # A handful of rows lose their key fields entirely.
    n_key_missing = max(int(n_rows * 0.0002), 2)
    key_picks = rng.choice(len(out), size=n_key_missing, replace=False)
    out.loc[key_picks[: n_key_missing // 2], TURBINE_ID] = None
    out.loc[key_picks[n_key_missing // 2 :], TIMESTAMP] = pd.NaT

    return out.sort_values([TURBINE_ID, TIMESTAMP], na_position="last").reset_index(drop=True)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def _steps_per_hour(freq: str) -> float:
    delta = pd.Timedelta(pd.tseries.frequencies.to_offset(freq))
    return pd.Timedelta("1h") / delta


def generate_scada_dataset(cfg: Config, inject_issues: bool = True) -> pd.DataFrame:
    """Generate the full multi-turbine synthetic SCADA dataset.

    Args:
        cfg: Merged configuration (must contain the ``synthetic`` section).
        inject_issues: Whether to add missing/invalid/duplicate records.

    Returns:
        A dataframe sorted by ``turbine_id`` then ``timestamp``.
    """
    seed = int(cfg.get("synthetic.seed", cfg.get("random_seed", 42)))
    n_turbines = int(cfg.require("synthetic.n_turbines"))
    freq = str(cfg.require("synthetic.freq"))
    months = int(cfg.require("synthetic.months"))
    start = pd.Timestamp(str(cfg.require("synthetic.start")))
    end = start + pd.DateOffset(months=months)

    index = pd.date_range(start=start, end=end, freq=freq, inclusive="left")
    steps = _steps_per_hour(freq)
    # Injected so downstream helpers can convert hours to row offsets.
    enriched = cfg.to_dict()
    enriched["synthetic"]["_steps_per_hour"] = steps
    cfg = Config(enriched)

    logger.info(
        "Generating synthetic SCADA data",
        extra={"turbines": n_turbines, "steps": len(index), "freq": freq},
    )

    n = len(index)
    site_rng = rng_for(seed, "site")
    day_of_year = index.dayofyear.to_numpy(dtype=float)
    hours = index.hour.to_numpy(dtype=float)
    ambient = (
        9.0
        + 11.0 * np.cos(2 * np.pi * (day_of_year - 200.0) / 365.25)
        + 3.6 * np.sin(2 * np.pi * (hours - 15.0) / 24.0)
        + _ou_process(n, site_rng, theta=0.05, sigma=0.5)
    )
    farm_driver = _ou_process(n, rng_for(seed, "farm_wind"), theta=0.03, sigma=0.42)

    profiles = build_profiles(n_turbines, seed)
    frames = [
        simulate_turbine(profile, index, ambient, farm_driver, cfg, seed)
        for profile in profiles
    ]
    dataset = pd.concat(frames, ignore_index=True)

    if inject_issues:
        dataset = inject_data_quality_issues(dataset, cfg, seed)

    dataset = dataset.sort_values([TURBINE_ID, TIMESTAMP], na_position="last").reset_index(drop=True)
    logger.info(
        "Synthetic dataset ready",
        extra={
            "rows": len(dataset),
            "failures": int(dataset[FAILURE_EVENT].sum()),
            "turbines": dataset[TURBINE_ID].nunique(),
        },
    )
    return dataset
